### ISSUE TITLE
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: 

### ISSUE THREAD

**Issue by Aquarian-Age** [Sylius/Sylius#10373]
**Sylius version affected**: 1.x.y
Sylius version v1.4.4

mysql --version
mysql  Ver 15.1 Distrib 10.2.22-MariaDB, for Linux (x86_64) using  EditLine wrapper

php -v
PHP 7.3.5 (cli) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.5, Copyright (c) 1998-2018 Zend Technologies

**Description**  

php bin/console sylius:install -v
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Undefined constant 'Container44iiUhd\srcApp_Kernel' in /home/xuan/work/sylius/var/cache/.env/srcApp_Kernel.envDebugContainer.php:5
Stack trace:
#0 /home/xuan/work/sylius/vendor/symfony/http-kernel/Kernel.php(567): require()
#1 /home/xuan/work/sylius/vendor/symfony/http-kernel/Kernel.php(133): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 /home/xuan/work/sylius/vendor/symfony/framework-bundle/Console/Application.php(65): Symfony\Component\HttpKernel\Kernel->boot()
#3 /home/xuan/work/sylius/vendor/symfony/console/Application.php(145): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /home/xuan/work/sylius/bin/console(38): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#5 {main}
  thrown in /home/xuan/work/sylius/var/cache/.env/srcApp_Kernel.envDebugContainer.php on line 5

**Steps to reproduce**  
openSUSE15.0
mkdir test && cd test
composer create-project sylius/sylius -vvv
cd sylius
cd config/packages/
cp nelmio_alice.yaml  dev/
mv nelmio_alice.yaml nelmio_alice.yaml.bak
cd -
composer dump-env .env

cat .env.local.php 

```
<?php

// This file was generated by running "composer dump-env .env"

return array (
  'APP_ENV' => '.env',
  'APP_DEBUG' => '1',
  'APP_SECRET' => 'EDITME',
  //'DATABASE_URL' => 'mysql://root@127.0.0.1/sylius_%kernel.environment%',
  'DATABASE_URL' => 'mysql://root:123456@127.0.0.1/sylius',
  'MAILER_URL' => 'smtp://localhost',
);
```

DATABASE_URL=mysql://root:123456@127.0.0.1/sylius
php bin/console sylius:install

**Comment by Aquarian-Age** [comment]
composer dump-env prob 
is work for me
