### ISSUE TITLE
EasyCodingStandard  - Fatal error

### ISSUE THREAD

**Issue by lukomwro** [Sylius/Sylius#12017]
**Sylius version affected**: 1.8

**Description**  
When I'm trying to run `vendor/bin/ecs check src tests` command I'm getting some php fatal error:
```bash
PHP Fatal error:  During class fetch: Uncaught ReflectionException: Class "Symplify\PackageBuilder\Console\HelpfulApplicationTrait" not found while loading "Symplify\EasyCodingStandard\Console\EasyCodingStandardConsoleApplication". in /app/vendor/symfony/config/Resource/ClassExistenceResource.php:181
Stack trace:
#0 [internal function]: Symfony\Component\Config\Resource\ClassExistenceResource::throwOnRequiredClass('Symplify\\Packag...')
#1 /app/vendor/symplify/easy-coding-standard/src/Console/EasyCodingStandardConsoleApplication.php(21): spl_autoload_call('Symplify\\Packag...')
#2 /app/vendor/squizlabs/php_codesniffer/autoload.php(169): include('/Users/lukom/Wo...')
#3 /app/vendor/squizlabs/php_codesniffer/autoload.php(134): PHP_CodeSniffer\Autoload::loadFile('/Users/lukom/Wo...')
#4 [internal function]: PHP_CodeSniffer\Autoload::load('Symplify\\EasyCo...')
#5 [internal function]: spl_autoload_call('Symplify\\EasyCo...')
#6 /Use in /app/vendor/symplify/easy-coding-standard/src/Console/EasyCodingStandardConsoleApplication.php on line 21

Fatal error: During class fetch: Uncaught ReflectionException: Class "Symplify\PackageBuilder\Console\HelpfulApplicationTrait" not found while loading "Symplify\EasyCodingStandard\Console\EasyCodingStandardConsoleApplication". in /app/vendor/symfony/config/Resource/ClassExistenceResource.php:181
Stack trace:
#0 [internal function]: Symfony\Component\Config\Resource\ClassExistenceResource::throwOnRequiredClass('Symplify\\Packag...')
#1 /app/vendor/symplify/easy-coding-standard/src/Console/EasyCodingStandardConsoleApplication.php(21): spl_autoload_call('Symplify\\Packag...')
#2 /app/vendor/squizlabs/php_codesniffer/autoload.php(169): include('/Users/lukom/Wo...')
#3 /app/vendor/squizlabs/php_codesniffer/autoload.php(134): PHP_CodeSniffer\Autoload::loadFile('/Users/lukom/Wo...')
#4 [internal function]: PHP_CodeSniffer\Autoload::load('Symplify\\EasyCo...')
#5 [internal function]: spl_autoload_call('Symplify\\EasyCo...')
#6 /Use in /app/vendor/symplify/easy-coding-standard/src/Console/EasyCodingStandardConsoleApplication.php on line 21

```
**Steps to reproduce**  
run `vendor/bin/ecs check src tests`

**Comment by lchrusciel** [comment]
Hey, thanks for reporting. Could you give it a try and resolve this issue?

**Comment by lamasfoker** [comment]
I think you get this error because [symplify/package-builder](https://github.com/symplify/package-builder) breaks the Semantic Version. The last [8.3.48](https://github.com/symplify/package-builder/releases/tag/8.3.48) release does not have `Symplify\PackageBuilder\Console\HelpfulApplicationTrait`

**Comment by ehibes** [comment]
So is there a solution for this ? We can't install paypal plugin with Sylius 1.8...

**Comment by lamasfoker** [comment]
@ehibes have you tried to update `symplify/package-builder`? One of my mates installed successfully the official sylius paypal plugin on the latest 1.8.

**Comment by ehibes** [comment]
I just managed to install `sylius/paypal-plugin` downgrading it to `v1.0.0-RC.1`. `symplify/package-builder` is `8.3.48`.

**Comment by lamasfoker** [comment]
Sorry for the message above. I have to say to downgrade the `symplify/package-builder` at least to `8.3.26`.

**Comment by lukomwro** [comment]
I've upgraded to the 1.10 and everything works fine. I'm closing this issue. Thx
