### ISSUE TITLE
Error running yarn build on fresh install

### ISSUE THREAD

**Issue by teratux** [Sylius/Sylius#12481]
**Sylius version affected**: 1.9

**Description**  
I'm following the official doc to install the latest version but it fails when running yarn build.

**Steps to reproduce**  
```
composer create-project sylius/sylius-standard acme
```
```
yarn install
```
```
yarn build
```

**Possible Solution**  
Possibly a dependency issue with babel, this is the error:
```
/home/teratux/w/inteliforja/proyectos/cubanmakers/web/web/node_modules/babel-core/lib/config/option-manager.js:122
      throw e;
      ^

Error: [BABEL] /home/teratux/w/inteliforja/proyectos/cubanmakers/web/web/gulpfile.babel.js: Requires Babel "^7.0.0-beta.41", but was loaded with "7.0.0-beta.3". You'll need to update your @babel/core version. (While processing: "/home/teratux/w/inteliforja/proyectos/cubanmakers/web/web/node_modules/@babel/plugin-proposal-object-rest-spread/lib/index.js")
    at throwVersionError (/home/teratux/w/inteliforja/proyectos/cubanmakers/web/web/node_modules/@babel/helper-plugin-utils/lib/index.js:76:11)
    at Object.assertVersion (/home/teratux/w/inteliforja/proyectos/cubanmakers/web/web/node_modules/@babel/helper-plugin-utils/lib/index.js:28:5)
    at /home/teratux/w/inteliforja/proyectos/cubanmakers/web/web/node_modules/@babel/plugin-proposal-object-rest-spread/lib/index.js:35:7
    at /home/teratux/w/inteliforja/proyectos/cubanmakers/web/web/node_modules/@babel/helper-plugin-utils/lib/index.js:22:12
    at /home/teratux/w/inteliforja/proyectos/cubanmakers/web/web/node_modules/babel-core/lib/config/option-manager.js:238:14
    at cachedFunction (/home/teratux/w/inteliforja/proyectos/cubanmakers/web/web/node_modules/babel-core/lib/config/caching.js:48:17)
    at loadPluginDescriptor (/home/teratux/w/inteliforja/proyectos/cubanmakers/web/web/node_modules/babel-core/lib/config/option-manager.js:272:28)
    at /home/teratux/w/inteliforja/proyectos/cubanmakers/web/web/node_modules/babel-core/lib/config/option-manager.js:56:14
    at Array.map (<anonymous>)
    at OptionManager.mergeOptions (/home/teratux/w/inteliforja/proyectos/cubanmakers/web/web/node_modules/babel-core/lib/config/option-manager.js:55:34)
    at OptionManager.init (/home/teratux/w/inteliforja/proyectos/cubanmakers/web/web/node_modules/babel-core/lib/config/option-manager.js:114:14)
    at manageOptions (/home/teratux/w/inteliforja/proyectos/cubanmakers/web/web/node_modules/babel-core/lib/config/option-manager.js:40:30)
    at loadConfig (/home/teratux/w/inteliforja/proyectos/cubanmakers/web/web/node_modules/babel-core/lib/config/index.js:17:37)
    at loadOptions (/home/teratux/w/inteliforja/proyectos/cubanmakers/web/web/node_modules/babel-core/lib/index.js:105:36)
    at OptionManager.init (/home/teratux/w/inteliforja/proyectos/cubanmakers/web/web/node_modules/babel-core/lib/index.js:115:12)
    at compile (/home/teratux/w/inteliforja/proyectos/cubanmakers/web/web/node_modules/babel-register/lib/node.js:56:40)
    at Module._compile (/home/teratux/w/inteliforja/proyectos/cubanmakers/web/web/node_modules/pirates/lib/index.js:86:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Object.newLoader [as .js] (/home/teratux/w/inteliforja/proyectos/cubanmakers/web/web/node_modules/pirates/lib/index.js:96:7)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at execute (/home/teratux/w/inteliforja/proyectos/cubanmakers/web/web/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:36:18)
    at Liftoff.handleArguments (/home/teratux/w/inteliforja/proyectos/cubanmakers/web/web/node_modules/gulp-cli/index.js:201:24) {
  code: 'BABEL_VERSION_UNSUPPORTED',
  version: '7.0.0-beta.3',
  range: '^7.0.0-0'
}
```

Yarn version: 1.16.0
Npm version: 7.7.3

**Comment by vvasiloi** [comment]
What's the NodeJS version?

**Comment by teratux** [comment]
> What's the NodeJS version?

v13.11.0, I updated yarn to the 1.22 version yesterday and I managed to build successfully.  I can continue now, but it would be good to know if there's a minimal version needed.

**Comment by vvasiloi** [comment]
I don't think Sylius can run with that version, try with 10, this is the one that's tested in the CI build.

**Comment by endelwar** [comment]
NodeJs 10 is not even in  maintenance see https://nodejs.org/en/about/releases/
I think that Sylius should run on NodeJS supported version (v16 would be good, as is the active LTS version)

**Comment by coldic3** [comment]
Hi all, since Sylius 1.11 we recommend using webpack, Sylius 1.12 has it by default :+1:
