### ISSUE TITLE
Error in installing Sylius with Docker in Swiftmailerbundle class

### ISSUE THREAD

**Issue by achraflamhamdi** [Sylius/Sylius#14428]
**Sylius version affected**: 1.12

I'm about starting learning Sylius, but when I follow docs for installation with Docker, In running "docker compose up -d" command, the steps don't complete so normal and an error shows up, it says that Swiftmailerbundle class is not found, it's shown as bellow

I reproduced the error many time and it persists

```
#49 5.819 Executing script cache:clear [KO]
#49 5.935  [KO]
#49 5.935 Script cache:clear returned with error code 255
#49 5.935 !!
#49 5.935 !!  Fatal error: Uncaught Error: Class "Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle" not found in /srv/sylius/src/Kernel.php:45
#49 5.935 !!  Stack trace:
#49 5.935 !!  #0 /srv/sylius/vendor/symfony/http-kernel/Kernel.php(386): App\Kernel->registerBundles()
#49 5.935 !!  #1 /srv/sylius/vendor/symfony/http-kernel/Kernel.php(786): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#49 5.935 !!  #2 /srv/sylius/vendor/symfony/http-kernel/Kernel.php(128): Symfony\Component\HttpKernel\Kernel->preBoot()
#49 5.935 !!  #3 /srv/sylius/vendor/symfony/framework-bundle/Console/Application.php(168): Symfony\Component\HttpKernel\Kernel->boot()
#49 5.935 !!  #4 /srv/sylius/vendor/symfony/framework-bundle/Console/Application.php(74): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
#49 5.935 !!  #5 /srv/sylius/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#49 5.935 !!  #6 /srv/sylius/bin/console(38): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#49 5.935 !!  #7 {main}
#49 5.935 !!    thrown in /srv/sylius/src/Kernel.php on line 45
#49 5.935 !!
#49 5.936 Script @auto-scripts was called via post-install-cmd
#49 ERROR: executor failed running [/bin/sh -c set -eux;     mkdir -p var/cache var/log;     composer dump-autoload --classmap-authoritative;     APP_SECRET='' composer run-script post-install-cmd;     chmod +x bin/console; sync;     bin/console sylius:install:assets --no-interaction;     bin/console sylius:theme:assets:install public --no-interaction]: exit code: 255
------
 > [sylius-standard-node base 20/22] RUN set -eux;     mkdir -p var/cache var/log;     composer dump-autoload --classmap-authoritative;     APP_SECRET='' composer run-script post-install-cmd;     chmod +x bin/console; sync;     bin/console sylius:install:assets --no-interaction;     bin/console sylius:theme:assets:install public --no-interaction:
#49 5.935 !!  #1 /srv/sylius/vendor/symfony/http-kernel/Kernel.php(786): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#49 5.935 !!  #2 /srv/sylius/vendor/symfony/http-kernel/Kernel.php(128): Symfony\Component\HttpKernel\Kernel->preBoot()
#49 5.935 !!  #3 /srv/sylius/vendor/symfony/framework-bundle/Console/Application.php(168): Symfony\Component\HttpKernel\Kernel->boot()
#49 5.935 !!  #4 /srv/sylius/vendor/symfony/framework-bundle/Console/Application.php(74): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
#49 5.935 !!  #5 /srv/sylius/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#49 5.935 !!  #6 /srv/sylius/bin/console(38): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#49 5.935 !!  #7 {main}
#49 5.935 !!    thrown in /srv/sylius/src/Kernel.php on line 45
#49 5.935 !!
#49 5.936 Script @auto-scripts was called via post-install-cmd
------
failed to solve: executor failed running [/bin/sh -c set -eux;     mkdir -p var/cache var/log;     composer dump-autoload --classmap-authoritative;     APP_SECRET='' composer run-script post-install-cmd;     chmod +x bin/console; sync;     bin/console sylius:install:assets --no-interaction;     bin/console sylius:theme:assets:install public --no-interaction]: exit code: 255
```

**Comment by huyta888** [comment]
Hi,
You can fix it by:
- Remove "Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::class => ['all' => true]," in /config/bundles.php
- Remove "swiftmailer.yaml" in /config/packages/

**Comment by achraflamhamdi** [comment]
> Hi, You can fix it by:
> 
> * Remove "Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::class => ['all' => true]," in /config/bundles.php
> * Remove "swiftmailer.yaml" in /config/packages/

thanks ! that worked
