### ISSUE TITLE
GULP address already in use :::35729 ...

### ISSUE THREAD

**Issue by rubencosta13** [Sylius/Sylius#14635]
**Sylius version affected**: 1.11.4

When running yarn build on the docker container I got the following error:
```
.. Uhoh. Got error listen EADDRINUSE: address already in use :::35729 ...
[gulp-chug] (vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/gulpfile.babel.js) Error: listen EADDRINUSE: address already in use :::35729
    at Server.setupListenHandle [as _listen2] (net.js:1331:16)
    at listenInCluster (net.js:1379:12)
    at Server.listen (net.js:1465:7)
    at Server.listen (/srv/sylius/node_modules/tiny-lr/src/server.js:264:19)
    at Function.exports.listen (/srv/sylius/node_modules/gulp-livereload/index.js:97:18)
    at watchShop (/srv/sylius/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/gulpfile.babel.js:241:14)
    at bound (domain.js:421:15)
    at runBound (domain.js:432:12)
    at asyncRunner (/srv/sylius/node_modules/async-done/index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

How can I fix this?

**Comment by rubencosta13** [comment]
Note: Changing the ports on gulp, makes it throw a 500 error when I try to access the page

**Comment by rubencosta13** [comment]
<img width="592" alt="image" src="https://user-images.githubusercontent.com/66113929/207283712-e8909c72-53fc-4a44-999a-ff7c5ac95253.png">

**Comment by everwhatever** [comment]
Hi @rubencosta13 
This bug is not connected with Sylius. You can try to find a solution on our Slack:  https://sylius-devs.slack.com/ssb/redirect

**Comment by Rafikooo** [comment]
As mentioned above, we are closing this ticket because it is not relevant to Sylius
