### ISSUE TITLE
installation error: Uncaught exception 'ReflectionException'

### ISSUE THREAD

**Issue by maneeshdisodia** [Sylius/Sylius#2473]
this is my console output:

Step 1 of 4. Checking system requirements.
PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Extension intl does not exist' in /var/www/sylius/src/Sylius/Bundle/InstallerBundle/Requirement/ExtensionsRequirements.php:131
Stack trace:
#0 /var/www/sylius/src/Sylius/Bundle/InstallerBundle/Requirement/ExtensionsRequirements.php(131): ReflectionExtension->__construct('intl')
#1 /var/www/sylius/app/cache/dev/appDevDebugProjectContainer.php(14041): Sylius\Bundle\InstallerBundle\Requirement\ExtensionsRequirements->__construct(Object(Symfony\Bundle\FrameworkBundle\Translation\Translator))
#2 /var/www/sylius/app/bootstrap.php.cache(2019): appDevDebugProjectContainer->getSylius_RequirementsService()
#3 /var/www/sylius/src/Sylius/Bundle/InstallerBundle/Command/AbstractInstallCommand.php(50): Symfony\Component\DependencyInjection\Container->get('sylius.requirem...')
#4 /var/www/sylius/src/Sylius/Bundle/InstallerBundle/Command/CheckRequirementsCommand.php(32): Sylius\Bundle\InstallerBundle\Command\AbstractInstallCommand->get('sylius.requirem...')
#5 /var/www/sy in /var/www/sylius/src/Sylius/Bundle/InstallerBundle/Requirement/ExtensionsRequirements.php on line 131

please help me out. 
Thanks

**Comment by maneeshdisodia** [comment]
thanks 
i install php5-intl
issue resolve  :)
