### ISSUE TITLE
Problem in instalation with yarn

### ISSUE THREAD

**Issue by juanitourquiza** [Sylius/Sylius#8188]
Hi,

I write this code:
`yarn install`

This is my error after the code:

```
yarn : El término 'yarn' no se reconoce como nombre de un cmdlet, función, archivo de
script o programa ejecutable. Compruebe si escribió correctamente el nombre o, si incluyó
una ruta de acceso, compruebe que dicha ruta es correcta e inténtelo de nuevo.
En línea: 1 Carácter: 1
+ yarn install
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (yarn:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

What is the problem?

Regards

**Comment by juanitourquiza** [comment]
Hi

I did not know the change within the project of **npm** for **yarn**
I read that yarn is much better
Install yarn with this code:
`npm install --global yarn`

Important to check this link:
https://yarnpkg.com/lang/en/docs/install/#alternatives-tab

Regards

**Comment by hazasaad** [comment]
C:\xampp\htdocs\project>yarn install
yarn install v1.3.2
[1/4] Resolving packages...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: This socket is closed
    at WriteStream.Socket._writeGeneric (net.js:679:19)
    at WriteStream.Socket._write (net.js:730:8)
    at doWrite (_stream_writable.js:331:12)
    at writeOrBuffer (_stream_writable.js:317:5)
    at WriteStream.Writable.write (_stream_writable.js:243:11)
    at WriteStream.Socket.write (net.js:657:40)
    at Console.warn (console.js:51:16)
    at C:\Program Files\Yarn\lib\cli.js:73181:5
    at Array.forEach (native)
    at EventEmitter.<anonymous> (C:\Program Files\Yarn\lib\cli.js:73174:24)
