### ISSUE TITLE
Yarn install command error

### ISSUE THREAD

**Issue by apoorva-shah** [Sylius/Sylius#8498]
After Sylius install.
I run yarn install and i get error...
ERROR: [Errno 2] No such file or directory: 'install'

**Comment by Koronos** [comment]
Can you add how you write the command please? It seems like a typo

**Comment by apoorva-shah** [comment]
Some how don't know it is solved now. thanks :)

**Comment by hazasaad** [comment]
i too had this problem
C:\xampp\htdocs\project>yarn install
yarn install v1.3.2
[1/4] Resolving packages...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: This socket is closed
    at WriteStream.Socket._writeGeneric (net.js:679:19)
    at WriteStream.Socket._write (net.js:730:8)
    at doWrite (_stream_writable.js:331:12)
    at writeOrBuffer (_stream_writable.js:317:5)
    at WriteStream.Writable.write (_stream_writable.js:243:11)
    at WriteStream.Socket.write (net.js:657:40)
    at Console.warn (console.js:51:16)
    at C:\Program Files\Yarn\lib\cli.js:73181:5
    at Array.forEach (native)
    at EventEmitter.<anonymous> (C:\Program Files\Yarn\lib\cli.js:73174:24)
